cook/urls.py
from django.urls import path
from .views import show_recipes_without_product, add_product_to_recipe, cook_recipe

app_name = 'cook'


urlpatterns = [
    path('show_recipes_without_product/', show_recipes_without_product, name='show_recipes_without_product'),
    path('add_product_to_recipe/', add_product_to_recipe,
         name='add_product_to_recipe'),
    path('cook_recipe/', cook_recipe, name='cook_recipe'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cook.urls'))
]

cook/models.py
from django.db import models


class Recipe(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = "Рецепты"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    cooked_times = models.IntegerField(default=0, verbose_name='Использовано')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = "Продукты"

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='ingredients')
    weight = models.IntegerField(default=0, verbose_name='Вес')

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = "Ингредиенты"

    def use_product(self):
        self.product.cooked_times += 1
        self.product.save()

cook/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.db import transaction
from cook.models import Product, Recipe, Ingredient
from django.db.models import Q


def show_recipes_without_product(request):
    product_id = request.GET.get('product_id')
    receipts = Recipe.objects.filter(
        ~Q(ingredients__product_id=product_id, ingredients__weight__gte=10)
    )

    return render(request, 'cook/index.html', context={
        'receipts': receipts,
        'product_id': product_id
    })


@transaction.atomic
def add_product_to_recipe(request):
    receipt_id = request.GET.get('receipt_id')
    product_id = request.GET.get('product_id')
    weight = request.GET.get('weight')
    recipe = get_object_or_404(Recipe, pk=receipt_id)
    product = get_object_or_404(Product, pk=product_id)
    Ingredient.objects.update_or_create(
        recipe=recipe,
        product=product,
        defaults={
            'weight': weight
        }
    )
    return redirect(reverse(f'cook:show_recipes_without_product') + f'?product_id={product_id}')


@transaction.atomic
def cook_recipe(request):
    receipt_id = request.GET.get('receipt_id')
    recipe = get_object_or_404(Recipe, pk=receipt_id)
    ingredients = Ingredient.objects.filter(recipe=recipe)
    for ingredient in ingredients:
        ingredient.use_product()
    return redirect('cook:show_recipes_without_product')

cook/templates/cook/index.html
<html>
<head>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Название Рецепта</th>
            <th>Добавить в рецепт</th>
        </tr>
    </thead>
    <tbody>
    {% for receipt in receipts %}
        <tr>
            <td> {{ receipt.id }}</td>
            <td>{{ receipt.name }}</td>
            <td>
                <form action="{% url 'cook:add_product_to_recipe' %}">
                    <input style="visibility: hidden" type="text" value={{ receipt.id }} id="recipeName" name="receipt_id" placeholder="Укажите вес продукта" required>
                    <input style="visibility: hidden" type="text" value={{ product_id }} id="recipeName" name="product_id" placeholder="Укажите вес продукта" required>
                    <input type="number" id="recipeName" name="weight" placeholder="Укажите вес продукта" required>
                    <button type="submit">submit</button>
                </form>
{#                <a href="{% url 'cook:add_product_to_recipe' %}?receipt_id={{receipt.id}}&product_id={{ product_id }}&weight=50"> Sumbit</a>#}
            </td>
{#            <td><input type="text" id="recipeName" name="recipeName" placeholder="Укажите вес продукта" required></td>#}

        </tr>
    {% endfor %}
    </tbody>
    </table>
</body>

</html>